---
- name: EVS XT-VIA Setup and Config Playbook
  hosts: xt-via
  gather_facts: false
  #vars_files: ../show_vars/TESTING.yaml
  vars:
    ansible_python_interpreter: "../.venv/bin/python"
  roles:
    - role: evs-xt-via
      tags: ['setup']
      delegate_to: 127.0.0.1