- name: XT-VIA Send Config Lines
  hosts: xt-via
  remote_user: root
  gather_facts: false

  vars:
    ansible_ssh_pass: evs!
    ansible_ssh_user: root
    serverNumber: "{{ inventory_hostname | regex_replace('^[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.\\d([0-9]{0,2})$', '\\1') }}"
    facilityName: "{{  'GCV-[TRUCK]-A-EVS-' + serverNumber }}"
    currentVersion: "21.00.21"
    currentVersionFile: "./software/Multicam_20_07_35/Multicam_20.07.35.84415.tar.gz"
    currentVersionName: "20.00.21.84415"
    updateVersion: false
    perferedServerNumber: 1
    truckOctet: 64
    xtVersion: "21.00.21"
  tasks:
    - name: Set Facility Name
      ansible.builtin.uri:
        url: http://{{ inventory_hostname }}/cfgweb/CfgWeb.dll/FacilityNameJS?SessionID=Reset&FacilityName={{ facilityName | string }}
        method: POST
        return_content: yes
      delegate_to: 127.0.0.1
      register: _result
      until: _result.json.FacilityName == '{{ facilityName | string }}'
      retries: 5
      delay: 5
      when: true

    - name: Print Result
      ansible.builtin.debug:
        msg: "{{ _result }}"
